### ISSUE TITLE
INN 2.4.5 crashing with Perl 5.8.9

### ISSUE THREAD

**Issue by rra** [InterNetNews/inn#139]
**Reported by jeff on 21 Jan 2009 02:41 UTC**
When INN 2.4.5 (but not 2.4.3), is compiled with perl support using Perl 5.8.9 (but not 5.8.8 or 5.10.0), innd crashes at startup.

gdb of the innd core shows: ```
#0  0x281bbd90 in Perl_doing_taint () from .../perl5/5.8.9/mach/CORE/libperl.so
#1  0x281bbdd4 in Perl_sys_init3 () from .../perl5/5.8.9/mach/CORE/libperl.so
#2  0x08090e74 in PERLsetup ()
#3  0x0805c088 in main ()
```


Reported separately by Marc G. Fournier and Michael Grimm.

**Comment by rra** [comment]
**Comment by jeff on 21 Jan 2009 02:43 UTC**
Both reports come from users with FreeBSD (one running 6.x and one running 7.1-p2).

**Comment by rra** [comment]
**Modified by jeff on 21 Jan 2009 02:44 UTC**

**Comment by rra** [comment]
**Comment by iulius on 21 Jan 2009 19:47 UTC**
Already fixed in both STABLE and CURRENT (see [an [7940](7938]) for STABLE INN 2.4.5).
